# -*- coding: utf-8 -*-
"""Regression_with_One_Variable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P0RxR1TPw_wuOVKZC1q_ep2Z3WJBHDh_
"""

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
df=pd.read_csv('gdrive/My Drive/HDPrice.csv')

df.shape

df

!pip install --upgrade --quiet gspread

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials
gc=gspread.authorize(GoogleCredentials.get_application_default())

worksheet=gc.open('SampleData').sheet1
cell_list=worksheet

rows=worksheet.get_all_values()
print(rows)

import pandas as pd
pd.DataFrame.from_records(rows)

